### ISSUE TITLE
Есть README?

### ISSUE THREAD

**Issue by juzznight** [T1murKO/poshel_dymok#1]
Непонятно откуда достать апишки и тд

**Comment by juzznight** [comment]
Запустил, но застревает на этапе ввода инвайт кода.
![Screenshot_1](https://github.com/T1murKO/poshel_dymok/assets/165172616/bd1fd130-89b4-42ca-8d1f-2023622d320e)
Через минуту вылетает с ошибкой:
Traceback (most recent call last):
  File "C:\Users\123\Desktop\poshel_dymok-main\camria.py", line 1380, in <module>
    wait_long.until(EC.element_to_be_clickable((By.XPATH, "//span[contains(text(), 'Play')]"))).click()
  File "C:\Users\123\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00007FF7351A70C2+63090]
        (No symbol) [0x00007FF735112D12]
        (No symbol) [0x00007FF734FAEC65]
        (No symbol) [0x00007FF734FF499D]
        (No symbol) [0x00007FF734FF4ADC]
        (No symbol) [0x00007FF735035B37]
        (No symbol) [0x00007FF73501701F]
        (No symbol) [0x00007FF735033412]
        (No symbol) [0x00007FF735016D83]
        (No symbol) [0x00007FF734FE83A8]
        (No symbol) [0x00007FF734FE9441]
        GetHandleVerifier [0x00007FF7355A262D+4238301]
        GetHandleVerifier [0x00007FF7355DF78D+4488509]
        GetHandleVerifier [0x00007FF7355D7A6F+4456479]
        GetHandleVerifier [0x00007FF735280606+953270]
        (No symbol) [0x00007FF73511E5DF]
        (No symbol) [0x00007FF7351192B4]
        (No symbol) [0x00007FF7351193EB]
        (No symbol) [0x00007FF735109C24]
        BaseThreadInitThunk [0x00007FF9A260257D+29]
        RtlUserThreadStart [0x00007FF9A318AA58+40]

**Comment by juzznight** [comment]
Разобрался. Нужно самому ввести инвайт код. Дальше скрипт подхватывает и ебашит. Только Еще проблема. Скрипт создает каждый раз новый кошелек. Как привязать свой? фразу я ввел, но всё равно создает новый.

**Comment by T1murKO** [comment]
Какие апишки?
